apiVersion: v1
kind: Pod
metadata:
  name: docker-pod
  namespace: jenkins
  labels:
    app: docker
spec:
  containers:
    - name: docker-cmds
      image: docker:1.12.6
      command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
      resources: 
        limits:
          cpu: 10m
          memory: 256Mi
        requests: 
          cpu: 5m 
          memory: 64Mi 
      env: 
        - name: DOCKER_HOST 
          value: tcp://localhost:2375 
    - name: docker-daemon 
      image: docker:1.12.6-dind 
      resources:
        limits:
          cpu: 20m
          memory: 512Mi
        requests: 
          cpu: 5m 
          memory: 64Mi 
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/lib/docker
  volumes: 
    - name: dockersock
      emptyDir: {}



