apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: team-magma
  labels:
    app:  bubble-front
    tier: frontend
    track: stable
spec:
  type: LoadBalancer
  selector:
    app:  bubble-front
    tier: frontend
    track: stable
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

