# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   namespace: team-magma
#   labels:
#     app:  magma-bubble
# spec:
#   selector:
#     app:  magma-bubble
#   ports:
#     - name: http
#       port: 4200
#       targetPort: 4200
#       protocol: TCP
