apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: team-magma
  labels:
    app:  magma-bubblefront
spec:
  selector:
    app:  magma-bubblefront
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    type: NodePort
