apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: team-magma
  labels:
    # name: team-magma-frontend
    app: frontend
spec:
  replicas: 1
  # minReadySeconds: 5
  # strategy: 
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: magmabubble
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: magmabubble
        tier: frontend
        track: stable
    spec:
      nodeSelector:
        name: w1
      containers:
      - name: frontend
        image: jaylopez/bubblefront:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
   