apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  # namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 4Gi