apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
  labels:
    app: postgres
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-east-1a
    - us-east-1b
    - us-east-1c