apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
  namespace: postgres
  labels:
    app: postgres
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true