apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  # namespace: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres-container
    image: postgres
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 5432
    env: 
       - name: POSTGRES_PASSWORD
         valueFrom:
          secretKeyRef:
            name: magma-bubble-secret
            key: password
       - name: PGDATA
         value: /var/lib/postgresql/data/pgdata
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: db-data
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: postgres-volume-claim