apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-claim
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgrews-storage
  resources:
    requests:
      storage: 4Gi