apiVersion: v1
kind: ConfigMap
metadata:
  name: magma-promtail-config
  namespace: team-magma
data:
  promtail.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: magma-bubble-logs
              __path__: /logs/*.log
              namespace: team-magma
        pipeline_stages:
          - json:
              expressions:
                level: level
          - labels:
              level: